### **CalCOFI Marine Mammal Visual Survey Data**

Marine mammal visual line-transect surveys have been conducted on quarterly CalCOFI cruises since 2004. Visual surveys are conducted during daylight hours while the ship is in transit between CalCOFI stations. More information about visual survey protocol can be found in [Campbell et al. (2015)](https://doi.org/10.1016/j.dsr2.2014.10.008","https://doi.org/10.1016/j.dsr2.2014.10.008). Per-cruise marine mammal visual survey effort is visible by clicking 'Display Visual Effort'. Additionally, sighting group size estimates are visible by selecting a species from the drop-down menu, where circle size on the map is proportional to group size. Only cetacean sightings are included in this interactive map. By selecting a sighting on the map, more information will pop up about that specific sighting.

<br/>

### **CalCOFI Marine Mammal eDNA Data**

The NOAA CalCOFI Genomic Program (NCOG) has collected envrionmental DNA samples (eDNA) since 2014. Here we used metabarcoding assays to detect cetacean species from water samples collected at 10, 20, or 40 meters. The 'Display eDNA' function will plot eDNA sampling effort as opaque black circles, and eDNA detections as blue flags. By selecting a detection on the map, more information about that specific detection will pop up.

<br/>

### **UCSB Data Science Capstone**

The Data Science Capstone is a three-course sequence at the University of California, Santa Barbara (UCSB) in which students engage in project-based learning with data-intensive methodologies with the hopes of making a positive impact on the world. As their project, seven students from the program upgraded this Shiny app to implement new data, improve functionality, and enhance user experience.

<br/>

### **Co-authors**

Michaela Alksne, Lauren Baggett, Julie Dinasquet, Bryce Ellman, Erin Satterthwaite, Brice Semmens, Simone Baumann-Pickering, Luis Barajas, Sam Guimte, Justin Kim, Kaitlyn Lee, Yoobin Won, Ryan Yee, and Puyuan Zhang.

<br/>

### **Funding Sources**

This material is based upon research supported by the Office of Naval Research under Award Number (N00014-22-1-2719).

Office of Naval Research, US Navy Pacific Fleet